create extension if not exists pgcrypto;
create extension if not exists citext;
create type user_role as enum ('OWNER','APPROVER','BUYER','AUDITOR');
create type batch_status as enum ('DRAFT','PRICING','AWAITING_APPROVAL','APPROVED','ORDERING','PARTIAL','COMPLETE','FAILED','CANCELLED');
create type order_status as enum ('QUEUED','REQUIRES_ACTION','PLACED','CONFIRMED','SHIPPED','DELIVERED','FAILED','CANCELLED','REFUNDED');

create table tenants (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table users (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), email citext not null, password_hash text not null, role user_role not null, active boolean not null default true, created_at timestamptz not null default now(), unique(tenant_id,email));
create table sessions (id_hash text primary key, user_id uuid not null references users(id) on delete cascade, expires_at timestamptz not null, created_at timestamptz not null default now());
create table address_books (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), name text not null, created_by uuid not null references users(id), created_at timestamptz not null default now());
create table addresses (id uuid primary key default gen_random_uuid(), address_book_id uuid not null references address_books(id) on delete cascade, recipient text not null, phone text not null, line1 text not null, line2 text, city text not null, state text not null, postal_code text not null, country char(2) not null default 'IN', reference text, unique(address_book_id, reference));
create table order_batches (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), name text not null, status batch_status not null default 'DRAFT', currency char(3) not null default 'INR', estimated_total_minor bigint not null default 0, approved_total_minor bigint, created_by uuid not null references users(id), approved_by uuid references users(id), approved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table batch_items (id uuid primary key default gen_random_uuid(), batch_id uuid not null references order_batches(id) on delete cascade, product_url text not null, retailer text not null, title text, sku text, unit_price_minor bigint, requested_quantity integer not null check(requested_quantity > 0), available_quantity integer, address_id uuid references addresses(id), pricing_status text not null default 'PENDING', pricing_checked_at timestamptz, unique(batch_id, product_url, address_id));
create table purchase_orders (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), batch_item_id uuid not null references batch_items(id), status order_status not null default 'QUEUED', retailer text not null, retailer_order_id text, amount_minor bigint, virtual_card_reference text, idempotency_key text not null unique, failure_code text, failure_message text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table provider_secrets (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references tenants(id), provider text not null, ciphertext bytea not null, iv bytea not null, auth_tag bytea not null, created_at timestamptz not null default now(), unique(tenant_id,provider));
create table audit_log (id bigserial primary key, tenant_id uuid not null references tenants(id), actor_id uuid references users(id), action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index audit_log_tenant_created_idx on audit_log(tenant_id, created_at desc);
create index batches_tenant_status_idx on order_batches(tenant_id,status);
create index orders_tenant_status_idx on purchase_orders(tenant_id,status);
