import Fastify from "fastify";
import cookie from "@fastify/cookie";
import helmet from "@fastify/helmet";
import rateLimit from "@fastify/rate-limit";
import staticPlugin from "@fastify/static";
import multipart from "@fastify/multipart";
import ExcelJS from "exceljs";
import { randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const port=Number(process.env.PORT??3000);
const email=(process.env.DEMO_EMAIL??"demo@ordergrid.in").toLowerCase();
const password=process.env.DEMO_PASSWORD??"OrderGridDemo2026!";
const secret=process.env.SESSION_SECRET??randomBytes(32).toString("hex");
const session=randomBytes(32).toString("base64url");
type Address={id:string;recipient:string;phone:string;line1:string;line2?:string;city:string;state:string;postal_code:string;country:string;reference?:string};
type Batch={id:string;name:string;status:string;currency:string;estimated_total_minor:number;created_at:string;item_count:number};
type Item={id:string;batchId:string;product_url:string;retailer:string;requested_quantity:number;addressId:string;unit_price_minor:number};
type Task={id:string;status:string;amount_minor:number;failure_message:string;product_url:string;title:string;requested_quantity:number;recipient:string;city:string;postal_code:string};
const addresses=new Map<string,Address>(),items:Item[]=[],batches:Batch[]=[],tasks:Task[]=[];
const app=Fastify({logger:true,trustProxy:true});
await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],imgSrc:["'self'","data:"]}}});
await app.register(rateLimit,{max:120,timeWindow:"1 minute"});
await app.register(cookie,{secret});
await app.register(multipart,{limits:{fileSize:5_000_000,files:1}});
await app.register(staticPlugin,{root:join(dirname(fileURLToPath(import.meta.url)),"../public"),prefix:"/"});
const same=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
app.addHook("preHandler",async(req,reply)=>{if(!req.url.startsWith("/api/")||req.url==="/api/health"||req.url==="/api/login")return;if(req.cookies.demo_session!==session)return reply.code(401).send({error:"unauthorized"});});
app.get("/api/health",async()=>({status:"ok",mode:"showroom"}));
app.post("/api/login",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(req,reply)=>{const body=z.object({email:z.string().email(),password:z.string()}).parse(req.body);if(!same(body.email.toLowerCase(),email)||!same(body.password,password))return reply.code(401).send({error:"invalid_credentials"});reply.setCookie("demo_session",session,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:43200});return {user:{role:"OWNER"}};});
app.post("/api/logout",async(_,reply)=>{reply.clearCookie("demo_session",{path:"/"});return {ok:true}});
app.get("/api/dashboard",async()=>{const batchGroups=new Map<string,Batch[]>(),taskGroups=new Map<string,Task[]>();for(const b of batches)batchGroups.set(b.status,[...(batchGroups.get(b.status)??[]),b]);for(const t of tasks)taskGroups.set(t.status,[...(taskGroups.get(t.status)??[]),t]);return {batches:[...batchGroups].map(([status,list])=>({status,count:list.length,total:list.reduce((n,b)=>n+b.estimated_total_minor,0)})),orders:[...taskGroups].map(([status,list])=>({status,count:list.length}))};});
app.get("/api/batches",async()=>({batches}));
app.get("/api/checkout-tasks",async()=>({tasks}));
app.post("/api/address-books/import",async(req,reply)=>{const file=await req.file();if(!file)return reply.code(400).send({error:"file_required"});const buffer=await file.toBuffer();let rows:string[][]=[];if(file.filename.toLowerCase().endsWith(".xlsx")){const book=new ExcelJS.Workbook();await book.xlsx.load(buffer as any);const sheet=book.worksheets[0];if(!sheet)return reply.code(400).send({error:"empty_workbook"});sheet.eachRow(r=>rows.push((r.values as any[]).slice(1).map(v=>String(v??"").trim())));}else rows=buffer.toString("utf8").replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean).map(line=>line.split(",").map(v=>v.trim().replace(/^"|"$/g,"")));
  if(rows.length<2)return reply.code(400).send({error:"no_address_rows"});const headers=rows[0]!.map(h=>h.toLowerCase().replace(/[ _-]+/g,"_"));for(const h of ["recipient","phone","line1","city","state","postal_code"])if(!headers.includes(h))return reply.code(400).send({error:"missing_column",column:h});const val=(row:string[],name:string)=>row[headers.indexOf(name)]??"";const ids:string[]=[];for(const row of rows.slice(1)){if(!row.some(Boolean))continue;const id=randomUUID();addresses.set(id,{id,recipient:val(row,"recipient"),phone:val(row,"phone"),line1:val(row,"line1"),line2:val(row,"line2"),city:val(row,"city"),state:val(row,"state"),postal_code:val(row,"postal_code"),country:val(row,"country")||"IN",reference:val(row,"reference")});ids.push(id);}return reply.code(201).send({addressBook:{id:randomUUID(),name:file.filename},addressIds:ids,count:ids.length});});
app.post("/api/batches",async(req,reply)=>{const input=z.object({name:z.string().min(3),items:z.array(z.object({productUrl:z.string().url(),quantity:z.number().int().positive(),addressId:z.string().uuid(),estimatedUnitPriceMinor:z.number().int().positive()})).min(1)}).parse(req.body);const id=randomUUID(),created_at=new Date().toISOString(),total=input.items.reduce((n,i)=>n+i.quantity*i.estimatedUnitPriceMinor,0);const batch={id,name:input.name,status:"AWAITING_APPROVAL",currency:"INR",estimated_total_minor:total,created_at,item_count:input.items.length};batches.unshift(batch);for(const i of input.items){const host=new URL(i.productUrl).hostname;items.push({id:randomUUID(),batchId:id,product_url:i.productUrl,retailer:host.includes("amazon.")?"amazon-in":host.includes("flipkart.")?"flipkart":host,requested_quantity:i.quantity,addressId:i.addressId,unit_price_minor:i.estimatedUnitPriceMinor});}return reply.code(201).send({id,status:batch.status});});
app.post("/api/batches/:id/approve",async(req,reply)=>{const id=z.string().uuid().parse((req.params as any).id),batch=batches.find(b=>b.id===id);if(!batch||batch.status!=="AWAITING_APPROVAL")return reply.code(409).send({error:"batch_not_approvable"});batch.status="APPROVED";for(const item of items.filter(i=>i.batchId===id)){const a=addresses.get(item.addressId)!;tasks.unshift({id:randomUUID(),status:"REQUIRES_ACTION",amount_minor:item.unit_price_minor*item.requested_quantity,failure_message:"Complete payment and any OTP on the retailer checkout page",product_url:item.product_url,title:"Retailer checkout",requested_quantity:item.requested_quantity,recipient:a.recipient,city:a.city,postal_code:a.postal_code});}return {ok:true};});
app.setErrorHandler((error,req,reply)=>{req.log.error(error);if(error instanceof z.ZodError)return reply.code(400).send({error:"invalid_request",issues:error.issues});return reply.code(500).send({error:"internal_error"});});
await app.listen({port,host:"0.0.0.0"});
