import Fastify from "fastify";
import cookie from "@fastify/cookie";
import helmet from "@fastify/helmet";
import rateLimit from "@fastify/rate-limit";
import staticPlugin from "@fastify/static";
import multipart from "@fastify/multipart";
import ExcelJS from "exceljs";
import { randomBytes, randomUUID } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { loadConfig } from "./config.js";
import { audit, createDb } from "./db.js";
import { hashPassword, tokenHash, verifyPassword } from "./security.js";
import { createOrderQueue } from "./queue.js";
import { checkoutHandoffUrl, retailerForProductUrl, validateRetailerOrderId } from "./assisted-checkout.js";
import { syncCheckoutBaskets } from "./baskets.js";

const config=loadConfig(), db=createDb(config), jobs=config.REDIS_URL?createOrderQueue(config.REDIS_URL):null;
const app=Fastify({logger:{redact:["req.headers.authorization","req.headers.cookie","password"]},trustProxy:true,requestIdHeader:"x-request-id",genReqId:()=>randomUUID()});
await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],imgSrc:["'self'","data:"]}}});
await app.register(rateLimit,{max:120,timeWindow:"1 minute"}); await app.register(cookie,{secret:config.SESSION_SECRET});
await app.register(multipart,{limits:{fileSize:5_000_000,files:1}});
await app.register(staticPlugin,{root:join(dirname(fileURLToPath(import.meta.url)),"../public"),prefix:"/"});

declare module "fastify" { interface FastifyRequest { principal?:{id:string;tenantId:string;role:string} } }
app.addHook("preHandler",async(req,reply)=>{ if(!req.url.startsWith("/api/")||req.url==="/api/health"||req.url==="/api/login")return; const raw=req.cookies.session; if(!raw)return reply.code(401).send({error:"unauthorized"}); const {rows}=await db.query(`select u.id,u.tenant_id,u.role from sessions s join users u on u.id=s.user_id where s.id_hash=$1 and s.expires_at>now() and u.active`,[tokenHash(raw)]); if(!rows[0])return reply.code(401).send({error:"unauthorized"}); req.principal={id:rows[0].id,tenantId:rows[0].tenant_id,role:rows[0].role}; });

app.get("/api/health",async()=>{await db.query("select 1");return {status:"ok"}});
app.post("/api/login",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(req,reply)=>{const input=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const {rows}=await db.query("select id,tenant_id,role,password_hash from users where email=$1 and active",[input.email.toLowerCase()]); const u=rows[0]; if(!u||!await verifyPassword(input.password,u.password_hash))return reply.code(401).send({error:"invalid_credentials"}); const token=randomBytes(32).toString("base64url"); await db.query("insert into sessions(id_hash,user_id,expires_at) values($1,$2,now()+interval '12 hours')",[tokenHash(token),u.id]); reply.setCookie("session",token,{httpOnly:true,secure:config.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:43200}); return {user:{id:u.id,role:u.role}};});
app.post("/api/logout",async(req,reply)=>{const raw=req.cookies.session;if(raw)await db.query("delete from sessions where id_hash=$1",[tokenHash(raw)]);reply.clearCookie("session",{path:"/"});return {ok:true}});
app.get("/api/dashboard",async(req)=>{const p=req.principal!;const [b,o]=await Promise.all([db.query("select status,count(*)::int count,coalesce(sum(estimated_total_minor),0)::bigint total from order_batches where tenant_id=$1 group by status",[p.tenantId]),db.query("select status,count(*)::int count from purchase_orders where tenant_id=$1 group by status",[p.tenantId])]);return {batches:b.rows,orders:o.rows};});
app.get("/api/batches",async(req)=>{const p=req.principal!;const {rows}=await db.query(`select b.id,b.name,b.status,b.currency,b.payment_route,b.estimated_total_minor,b.created_at,count(i.id)::int item_count from order_batches b left join batch_items i on i.batch_id=b.id where b.tenant_id=$1 group by b.id order by b.created_at desc limit 100`,[p.tenantId]);return {batches:rows};});
app.post("/api/address-books/import",async(req,reply)=>{const p=req.principal!;const file=await req.file();if(!file)return reply.code(400).send({error:"file_required"});const buffer=await file.toBuffer();let rows:string[][]=[];if(file.filename.toLowerCase().endsWith(".xlsx")){const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer as any);const sheet=workbook.worksheets[0];if(!sheet)return reply.code(400).send({error:"empty_workbook"});sheet.eachRow(r=>rows.push((r.values as any[]).slice(1).map(v=>String(v??"").trim())));}else{rows=buffer.toString("utf8").replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean).map(line=>line.split(",").map(v=>v.trim().replace(/^"|"$/g,"")));}if(rows.length<2)return reply.code(400).send({error:"no_address_rows"});const headers=rows[0]!.map(h=>h.toLowerCase().replace(/[ _-]+/g,"_"));const required=["recipient","phone","line1","city","state","postal_code"];for(const h of required)if(!headers.includes(h))return reply.code(400).send({error:"missing_column",column:h});const value=(row:string[],name:string)=>row[headers.indexOf(name)]??"";const c=await db.connect();try{await c.query("begin");const book=await c.query("insert into address_books(tenant_id,name,created_by) values($1,$2,$3) returning id,name",[p.tenantId,file.filename.replace(/\.[^.]+$/,"").slice(0,120),p.id]);const ids:string[]=[];for(const row of rows.slice(1)){if(!row.some(Boolean))continue;const phone=value(row,"phone").replace(/\D/g,"");const postal=value(row,"postal_code").replace(/\D/g,"");if(phone.length<10||postal.length!==6)throw new Error("Invalid phone or postal code in address file");const inserted=await c.query(`insert into addresses(address_book_id,recipient,phone,line1,line2,city,state,postal_code,country,reference) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id`,[book.rows[0].id,value(row,"recipient"),phone,value(row,"line1"),value(row,"line2")||null,value(row,"city"),value(row,"state"),postal,(value(row,"country")||"IN").toUpperCase(),value(row,"reference")||null]);ids.push(inserted.rows[0].id);}if(!ids.length)throw new Error("No valid address rows");await c.query("commit");await audit(db,p.tenantId,p.id,"address_book.imported","address_book",book.rows[0].id,{count:ids.length});return reply.code(201).send({addressBook:book.rows[0],addressIds:ids,count:ids.length});}catch(e){await c.query("rollback");throw e}finally{c.release()}});
app.get("/api/checkout-tasks",async(req)=>{const p=req.principal!;const {rows}=await db.query(`select po.id,po.status,po.amount_minor,po.failure_message,bi.product_url,bi.title,bi.requested_quantity,a.recipient,a.city,a.postal_code from purchase_orders po join batch_items bi on bi.id=po.batch_item_id left join addresses a on a.id=bi.address_id where po.tenant_id=$1 order by po.created_at desc limit 250`,[p.tenantId]);return {tasks:rows};});

app.get("/api/bulk-baskets",async(req)=>{const p=req.principal!;await db.query("update checkout_baskets set status='READY',claimed_by=null,expires_at=null,updated_at=now() where tenant_id=$1 and status in ('CLAIMED','OPENED') and expires_at<=now()",[p.tenantId]);const {rows}=await db.query(`
  select cb.id,cb.batch_id,cb.status,cb.retailer,cb.account_reference,cb.expires_at,
         a.recipient,a.city,a.postal_code,b.name batch_name,b.payment_route,
         count(po.id)::int item_count,coalesce(sum(po.amount_minor),0)::bigint amount_minor
  from checkout_baskets cb
  join order_batches b on b.id=cb.batch_id
  join addresses a on a.id=cb.address_id
  left join purchase_orders po on po.checkout_basket_id=cb.id
  where cb.tenant_id=$1
  group by cb.id,a.recipient,a.city,a.postal_code,b.name,b.payment_route
  order by cb.created_at desc limit 250
`,[p.tenantId]);return {baskets:rows};});

app.post("/api/bulk-queue/claim",async(req,reply)=>{const p=req.principal!;if(!["OWNER","APPROVER","BUYER"].includes(p.role))return reply.code(403).send({error:"forbidden"});const {limit}=z.object({limit:z.number().int().min(1).max(25).default(10)}).parse(req.body??{});const client=await db.connect();try{await client.query("begin");await client.query("update checkout_baskets set status='READY',claimed_by=null,expires_at=null,updated_at=now() where tenant_id=$1 and status in ('CLAIMED','OPENED') and expires_at<=now()",[p.tenantId]);const picked=await client.query("select id from checkout_baskets where tenant_id=$1 and status='READY' order by created_at for update skip locked limit $2",[p.tenantId,limit]);const ids:string[]=[];for(const row of picked.rows){await client.query("update checkout_baskets set status='CLAIMED',claimed_by=$1,expires_at=now()+interval '20 minutes',updated_at=now() where id=$2",[p.id,row.id]);ids.push(row.id);}await client.query("commit");await audit(db,p.tenantId,p.id,"bulk_queue.claimed","checkout_basket",null,{count:ids.length});return {claimed:ids.length,ids};}catch(e){await client.query("rollback");throw e}finally{client.release()}});

app.get("/api/bulk-queue",async(req)=>{const p=req.principal!;await db.query("update checkout_baskets set status='READY',claimed_by=null,expires_at=null,updated_at=now() where tenant_id=$1 and status in ('CLAIMED','OPENED') and expires_at<=now()",[p.tenantId]);const {rows}=await db.query(`
  select cb.id,cb.status,cb.retailer,cb.account_reference,cb.expires_at,cb.opened_at,
         a.recipient,a.city,a.postal_code,b.name batch_name,b.payment_route,
         count(po.id)::int item_count,coalesce(sum(po.amount_minor),0)::bigint amount_minor
  from checkout_baskets cb
  join order_batches b on b.id=cb.batch_id
  join addresses a on a.id=cb.address_id
  left join purchase_orders po on po.checkout_basket_id=cb.id
  where cb.tenant_id=$1 and cb.claimed_by=$2 and cb.status in ('CLAIMED','OPENED')
  group by cb.id,a.recipient,a.city,a.postal_code,b.name,b.payment_route
  order by cb.created_at
`,[p.tenantId,p.id]);return {baskets:rows};});

app.post("/api/bulk-queue/:id/open",async(req,reply)=>{const p=req.principal!,id=z.string().uuid().parse((req.params as any).id);const {rows}=await db.query("update checkout_baskets set status='OPENED',opened_at=coalesce(opened_at,now()),updated_at=now() where id=$1 and tenant_id=$2 and claimed_by=$3 and status in ('CLAIMED','OPENED') and expires_at>now() returning id,retailer,account_reference",[id,p.tenantId,p.id]);if(!rows[0])return reply.code(409).send({error:"basket_unavailable_or_expired"});const items=await db.query(`
  select po.id purchase_order_id,bi.product_url,bi.title,bi.requested_quantity,po.amount_minor
  from purchase_orders po join batch_items bi on bi.id=po.batch_item_id
  where po.checkout_basket_id=$1 and po.tenant_id=$2
  order by bi.created_at nulls last,po.created_at
`,[id,p.tenantId]).catch(async()=>db.query(`
  select po.id purchase_order_id,bi.product_url,bi.title,bi.requested_quantity,po.amount_minor
  from purchase_orders po join batch_items bi on bi.id=po.batch_item_id
  where po.checkout_basket_id=$1 and po.tenant_id=$2
  order by po.created_at
`,[id,p.tenantId]));const prepared=items.rows.map(item=>({...item,actionUrl:checkoutHandoffUrl(item.product_url)}));await audit(db,p.tenantId,p.id,"bulk_basket.opened","checkout_basket",id,{items:prepared.length});reply.header("cache-control","no-store");return {basketId:id,retailer:rows[0].retailer,accountReference:rows[0].account_reference,items:prepared};});

app.post("/api/bulk-queue/:id/confirm",async(req,reply)=>{const p=req.principal!,id=z.string().uuid().parse((req.params as any).id),body=z.object({retailerOrderId:z.string().min(3).max(80)}).parse(req.body),retailerOrderId=validateRetailerOrderId(body.retailerOrderId),client=await db.connect();try{await client.query("begin");const locked=await client.query("select batch_id from checkout_baskets where id=$1 and tenant_id=$2 and claimed_by=$3 and status in ('CLAIMED','OPENED') and expires_at>now() for update",[id,p.tenantId,p.id]);if(!locked.rows[0]){await client.query("rollback");return reply.code(409).send({error:"basket_unavailable_or_expired"})}await client.query("update purchase_orders set status='CONFIRMED',retailer_order_id=$1,failure_code=null,failure_message=null,updated_at=now() where checkout_basket_id=$2 and tenant_id=$3 and status in ('REQUIRES_ACTION','PLACED')",[retailerOrderId,id,p.tenantId]);await client.query("update checkout_baskets set status='CONFIRMED',retailer_order_id=$1,confirmed_at=now(),updated_at=now() where id=$2",[retailerOrderId,id]);await client.query("update order_batches b set status=case when not exists(select 1 from checkout_baskets x where x.batch_id=b.id and x.status<>'CONFIRMED') then 'COMPLETE' else 'PARTIAL' end,updated_at=now() where b.id=$1",[locked.rows[0].batch_id]);await client.query("commit");await audit(db,p.tenantId,p.id,"bulk_basket.confirmed","checkout_basket",id,{retailerOrderId});return {id,status:"CONFIRMED",retailerOrderId};}catch(e){await client.query("rollback");throw e}finally{client.release()}});

app.post("/api/bulk-queue/:id/release",async(req,reply)=>{const p=req.principal!,id=z.string().uuid().parse((req.params as any).id);const {rowCount}=await db.query("update checkout_baskets set status='READY',claimed_by=null,expires_at=null,opened_at=null,updated_at=now() where id=$1 and tenant_id=$2 and claimed_by=$3 and status in ('CLAIMED','OPENED')",[id,p.tenantId,p.id]);if(!rowCount)return reply.code(404).send({error:"basket_not_found"});await audit(db,p.tenantId,p.id,"bulk_basket.released","checkout_basket",id);return {ok:true}});

app.post("/api/operator-queue/claim",async(req,reply)=>{const p=req.principal!;if(!["OWNER","APPROVER","BUYER"].includes(p.role))return reply.code(403).send({error:"forbidden"});const {limit}=z.object({limit:z.number().int().min(1).max(25).default(10)}).parse(req.body??{});const c=await db.connect();try{await c.query("begin");await c.query("update checkout_sessions set status='EXPIRED',updated_at=now() where tenant_id=$1 and status in ('CLAIMED','OPENED') and expires_at<=now()",[p.tenantId]);const {rows}=await c.query(`select po.id,po.retailer,bi.product_url,a.reference account_reference,a.recipient,a.city,a.postal_code,po.amount_minor from purchase_orders po join batch_items bi on bi.id=po.batch_item_id left join addresses a on a.id=bi.address_id where po.tenant_id=$1 and po.status='REQUIRES_ACTION' and not exists(select 1 from checkout_sessions s where s.purchase_order_id=po.id and s.status in ('CLAIMED','OPENED','CONFIRMED')) order by po.created_at for update of po skip locked limit $2`,[p.tenantId,limit]);const sessions=[];for(const order of rows){const retailer=retailerForProductUrl(order.product_url);const result=await c.query(`insert into checkout_sessions(tenant_id,purchase_order_id,claimed_by,retailer_host,expires_at) values($1,$2,$3,$4,now()+interval '20 minutes') returning id,status,expires_at`,[p.tenantId,order.id,p.id,retailer.host]);sessions.push({...result.rows[0],...order,product_url:undefined});}await c.query("commit");await audit(db,p.tenantId,p.id,"operator_queue.claimed","checkout_session",null,{count:sessions.length});return {sessions};}catch(e){await c.query("rollback");throw e}finally{c.release()}});
app.get("/api/operator-queue",async req=>{const p=req.principal!;await db.query("update checkout_sessions set status='EXPIRED',updated_at=now() where tenant_id=$1 and status in ('CLAIMED','OPENED') and expires_at<=now()",[p.tenantId]);const {rows}=await db.query(`select s.id,s.status,s.expires_at,s.opened_at,s.confirmed_at,po.id purchase_order_id,po.retailer,po.retailer_order_id,po.amount_minor,bi.product_url,a.reference account_reference,a.recipient,a.city,a.postal_code from checkout_sessions s join purchase_orders po on po.id=s.purchase_order_id join batch_items bi on bi.id=po.batch_item_id left join addresses a on a.id=bi.address_id where s.tenant_id=$1 and s.claimed_by=$2 and s.status in ('CLAIMED','OPENED') order by s.created_at limit 100`,[p.tenantId,p.id]);return {sessions:rows};});
app.post("/api/operator-queue/:id/open",async(req,reply)=>{const p=req.principal!;const id=z.string().uuid().parse((req.params as any).id);const {rows}=await db.query(`update checkout_sessions s set status='OPENED',opened_at=coalesce(opened_at,now()),updated_at=now() from purchase_orders po,batch_items bi where s.id=$1 and s.tenant_id=$2 and s.claimed_by=$3 and s.status in ('CLAIMED','OPENED') and s.expires_at>now() and po.id=s.purchase_order_id and bi.id=po.batch_item_id returning s.id,bi.product_url`,[id,p.tenantId,p.id]);if(!rows[0])return reply.code(409).send({error:"session_unavailable_or_expired"});const actionUrl=checkoutHandoffUrl(rows[0].product_url);await audit(db,p.tenantId,p.id,"checkout_session.opened","checkout_session",id);reply.header("cache-control","no-store");return {sessionId:id,actionUrl};});
app.post("/api/operator-queue/:id/confirm",async(req,reply)=>{const p=req.principal!;const id=z.string().uuid().parse((req.params as any).id),body=z.object({retailerOrderId:z.string().min(3).max(80)}).parse(req.body),orderId=validateRetailerOrderId(body.retailerOrderId),c=await db.connect();try{await c.query("begin");const {rows}=await c.query(`select purchase_order_id from checkout_sessions where id=$1 and tenant_id=$2 and claimed_by=$3 and status in ('CLAIMED','OPENED') and expires_at>now() for update`,[id,p.tenantId,p.id]);if(!rows[0]){await c.query("rollback");return reply.code(409).send({error:"session_unavailable_or_expired"})}await c.query("update purchase_orders set status='CONFIRMED',retailer_order_id=$1,failure_code=null,failure_message=null,updated_at=now() where id=$2 and tenant_id=$3 and status='REQUIRES_ACTION'",[orderId,rows[0].purchase_order_id,p.tenantId]);await c.query("update checkout_sessions set status='CONFIRMED',confirmed_at=now(),updated_at=now() where id=$1",[id]);await c.query("commit");await audit(db,p.tenantId,p.id,"checkout_session.confirmed","checkout_session",id,{retailerOrderId:orderId});return {id,status:"CONFIRMED",retailerOrderId:orderId};}catch(e){await c.query("rollback");throw e}finally{c.release()}});
app.post("/api/operator-queue/:id/release",async(req,reply)=>{const p=req.principal!,id=z.string().uuid().parse((req.params as any).id);const {rowCount}=await db.query("delete from checkout_sessions where id=$1 and tenant_id=$2 and claimed_by=$3 and status in ('CLAIMED','OPENED')",[id,p.tenantId,p.id]);if(!rowCount)return reply.code(404).send({error:"session_not_found"});await audit(db,p.tenantId,p.id,"checkout_session.released","checkout_session",id);return {ok:true}});
app.get("/api/reports/orders.csv",async(req,reply)=>{const p=req.principal!;const {rows}=await db.query(`select po.id,po.status,po.retailer,po.retailer_order_id,po.amount_minor,po.failure_code,po.failure_message,a.recipient,a.city,a.postal_code,po.updated_at from purchase_orders po join batch_items bi on bi.id=po.batch_item_id left join addresses a on a.id=bi.address_id where po.tenant_id=$1 order by po.created_at`,[p.tenantId]);const csvCell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const columns=["id","status","retailer","retailer_order_id","amount_minor","failure_code","failure_message","recipient","city","postal_code","updated_at"];const csv=[columns.join(","),...rows.map(r=>columns.map(k=>csvCell(r[k])).join(","))].join("\n");reply.header("content-type","text/csv; charset=utf-8").header("content-disposition",'attachment; filename="ordergrid-orders.csv"');return csv;});

app.post("/api/checkout-tasks/:id/handoff",async(req,reply)=>{const p=req.principal!;const id=z.string().uuid().parse((req.params as any).id);const {rows}=await db.query(`select po.id,po.status,po.retailer,bi.product_url from purchase_orders po join batch_items bi on bi.id=po.batch_item_id where po.id=$1 and po.tenant_id=$2`,[id,p.tenantId]);const order=rows[0];if(!order)return reply.code(404).send({error:"checkout_task_not_found"});if(order.status!=="REQUIRES_ACTION")return reply.code(409).send({error:"checkout_task_not_actionable",status:order.status});const retailer=retailerForProductUrl(order.product_url);const actionUrl=checkoutHandoffUrl(order.product_url);await audit(db,p.tenantId,p.id,"checkout.handoff_opened","purchase_order",id,{retailer:retailer.id});reply.header("cache-control","no-store");return {taskId:id,retailer,actionUrl,status:"AWAITING_RETAILER_CONFIRMATION"};});
app.post("/api/checkout-tasks/:id/confirm",async(req,reply)=>{const p=req.principal!;if(!["OWNER","APPROVER","BUYER"].includes(p.role))return reply.code(403).send({error:"forbidden"});const id=z.string().uuid().parse((req.params as any).id);const body=z.object({retailerOrderId:z.string().min(3).max(80)}).parse(req.body);const retailerOrderId=validateRetailerOrderId(body.retailerOrderId);const {rows}=await db.query(`update purchase_orders set status='CONFIRMED',retailer_order_id=$1,failure_code=null,failure_message=null,updated_at=now() where id=$2 and tenant_id=$3 and status in ('REQUIRES_ACTION','PLACED') returning id,status,retailer,retailer_order_id`,[retailerOrderId,id,p.tenantId]);if(!rows[0])return reply.code(409).send({error:"checkout_task_not_confirmable"});await audit(db,p.tenantId,p.id,"checkout.retailer_confirmed","purchase_order",id,{retailerOrderId});return rows[0];});

app.post("/api/batches",async(req,reply)=>{const p=req.principal!;const input=z.object({name:z.string().min(3).max(120),paymentRoute:z.enum(["Corporate virtual card","Cash on Delivery"]).default("Corporate virtual card"),items:z.array(z.object({productUrl:z.string().url(),quantity:z.number().int().positive().max(10000),addressId:z.string().uuid().optional(),estimatedUnitPriceMinor:z.number().int().positive().optional()})).min(1).max(5000)}).parse(req.body); const c=await db.connect();try{await c.query("begin");const fullyEstimated=input.items.every(i=>i.estimatedUnitPriceMinor);if(!fullyEstimated&&!jobs)return reply.code(422).send({error:"estimated_price_required"});const total=input.items.reduce((sum,i)=>sum+(i.estimatedUnitPriceMinor??0)*i.quantity,0);const b=await c.query("insert into order_batches(tenant_id,name,created_by,status,estimated_total_minor,payment_route) values($1,$2,$3,$4,$5,$6) returning id,status",[p.tenantId,input.name,fullyEstimated?"AWAITING_APPROVAL":"DRAFT",total,input.paymentRoute]);for(const item of input.items){const retailer=retailerForProductUrl(item.productUrl).id;await c.query("insert into batch_items(batch_id,product_url,retailer,requested_quantity,address_id,unit_price_minor,pricing_status,pricing_checked_at) values($1,$2,$3,$4,$5,$6,$7,$8)",[b.rows[0].id,item.productUrl,retailer,item.quantity,item.addressId??null,item.estimatedUnitPriceMinor??null,item.estimatedUnitPriceMinor?"ESTIMATED":"PENDING",item.estimatedUnitPriceMinor?new Date():null]);}await c.query("commit");await audit(db,p.tenantId,p.id,"batch.created","order_batch",b.rows[0].id,{items:input.items.length,total});if(!fullyEstimated&&jobs)await jobs.queue.add("price-batch",{batchId:b.rows[0].id,tenantId:p.tenantId},{jobId:`price:${b.rows[0].id}`,attempts:5,backoff:{type:"exponential",delay:2000},removeOnComplete:1000});return reply.code(201).send(b.rows[0]);}catch(e){await c.query("rollback");throw e}finally{c.release()}});
app.post("/api/batches/:id/approve",async(req,reply)=>{const p=req.principal!;if(!["OWNER","APPROVER"].includes(p.role))return reply.code(403).send({error:"forbidden"});const id=z.string().uuid().parse((req.params as any).id);const {rows}=await db.query("update order_batches set status='APPROVED',approved_by=$1,approved_at=now(),updated_at=now() where id=$2 and tenant_id=$3 and status='AWAITING_APPROVAL' returning id",[p.id,id,p.tenantId]);if(!rows[0])return reply.code(409).send({error:"batch_not_approvable"});await audit(db,p.tenantId,p.id,"batch.approved","order_batch",id);if(jobs){await jobs.queue.add("place-batch",{batchId:id,tenantId:p.tenantId},{jobId:`place:${id}`,attempts:3,backoff:{type:"exponential",delay:5000}});}else{await db.query(`insert into purchase_orders(tenant_id,batch_item_id,status,retailer,amount_minor,idempotency_key,failure_code,failure_message) select $1,i.id,\'REQUIRES_ACTION\',i.retailer,i.unit_price_minor*i.requested_quantity,$2||i.id,\'BASKET_CHECKOUT_REQUIRED\',\'Grouped checkout basket is ready for execution\' from batch_items i where i.batch_id=$3 on conflict(idempotency_key) do nothing`,[p.tenantId,`basket:${id}:`,id]);await syncCheckoutBaskets(db,p.tenantId,id);}return {ok:true};});
app.get("/*",(_,reply)=>reply.sendFile("index.html"));
app.setErrorHandler((error,req,reply)=>{req.log.error(error);if(error instanceof z.ZodError)return reply.code(400).send({error:"invalid_request",issues:error.issues});return reply.code(500).send({error:"internal_error",requestId:req.id});});

async function bootstrap(){const {rows}=await db.query("select count(*)::int count from users");if(rows[0].count)return;const c=await db.connect();try{await c.query("begin");const t=await c.query("insert into tenants(name) values('OrderGrid') returning id");await c.query("insert into users(tenant_id,email,password_hash,role) values($1,$2,$3,'OWNER')",[t.rows[0].id,config.BOOTSTRAP_ADMIN_EMAIL.toLowerCase(),await hashPassword(config.BOOTSTRAP_ADMIN_PASSWORD)]);await c.query("commit");}catch(e){await c.query("rollback");throw e}finally{c.release()}}
await bootstrap(); await app.listen({port:config.PORT,host:"0.0.0.0"});
for(const sig of ["SIGTERM","SIGINT"] as const)process.on(sig,async()=>{await app.close();if(jobs){await jobs.queue.close();jobs.connection.disconnect();}await db.end();process.exit(0)});
